right_format = """$cmd_duration$time"""

[username]
style_user = "yellow bold"
style_root = "red bold"
format = "[synoet::]($style)"
disabled = false
show_always = true

[git_branch]
symbol = ""
truncation_symbol = ""
format= "[$branch]($style) "

[git_metrics]
added_style = "bold blue"
deleted_style = "bold red"
format = '\[[+$added]($added_style) [-$deleted]($deleted_style)\] '
only_nonzero_diffs = false
disabled = false

[cmd_duration]
min_time = 5
format = "[$duration](white)"

[time]
disabled = false
style = "white"
format = '  [\[ $time \]]($style) '
time_format = "%T"

[nodejs]
disabled = true

[python]
disabled = false
