right_format = """$cmd_duration$time"""
add_newline = true

[username]
style_user = "yellow"
style_root = "red"
format = "[synoet::]($style)"
disabled = false
show_always = true

[git_branch]
symbol = ""
truncation_symbol = ""
format= "[$branch]($style) "

[git_metrics]
added_style = "blue"
deleted_style = "red"
format = '\[[+$added]($added_style) [-$deleted]($deleted_style)\] '
only_nonzero_diffs = false
disabled = false

[cmd_duration]
min_time = 5
format = "[$duration](white)"

[time]
disabled = false
style = "white"
format = '  [\[ $time \]]($style) '
time_format = "%T"

[nodejs]
disabled = true

[python]
disabled = false

[aws]
disabled = true

[rust]
disabled = true

[docker_context]
disabled = true

[lua]
disabled = true
