return {
  -- {
  --   "AstroNvim/astroui",
  --   ---@type AstroUIOpts
  --   opts = {
  --     colorscheme = "ayu",
  --   },
  -- },
  -- {
  --   "shatur/neovim-ayu",
  --   init = function()
  --     vim.cmd [[
  --       if has('termguicolors')
  --         set termguicolors
  --       endif
  --     ]]
  --     -- vim.cmd [[let g:everforest_background = 'hard']]
  --     -- vim.cmd [[colorscheme everforest]]
  --     vim.cmd [[set clipboard+=unnamedplus]]
  --     vim.cmd [[set encoding=UTF-8]]
  --   end,
  -- },
}
