return {
  -- {
  --   "AstroNvim/astroui",
  --   ---@type AstroUIOpts
  --   opts = {
  --     colorscheme = "tokyonight-moon",
  --   },
  -- },
  -- {
  --   "folke/tokyonight.nvim",
  --   init = function()
  --     vim.cmd [[
  --       if has('termguicolors')
  --         set termguicolors
  --       endif
  --     ]]
  --     vim.cmd [[colorscheme tokyonight-moon]]
  --     vim.cmd [[set clipboard+=unnamedplus]]
  --     vim.cmd [[set encoding=UTF-8]]
  --   end,
  -- },
}
